### PR TITLE
Add reference deployment for Kube2IAM

### PR DESCRIPTION
**Pull request by the-smooth-operator**

### CODE REVIEW

**Comment by mozafrank** [comment]
@The-smooth-operator this looks great, can you explain how this would fit into how we use k8s clusters? Can you provide an example use case?

**Comment by the-smooth-operator** [comment]
Of course @mozafrank thanks for the question.

Kube2IAM assigns IAM roles to Pods running in Kubernetes in AWS via annotations, whether the cluster is EKS, kops... Currently EKS is not really integrated with IAM, because of that we need kube2IAM.

Traditionally, in order to limit the access to certain AWS resources without having to deal with API keys, we assign a role to an EC2 instance. All the applications running in that instance were given that role.
This is not really an option when using Kubernetes, because a single ec2 instance can be shared by several pods, each one pertaining to different projects, which need access to different resources.
Kube2IAM solves this problem in a very interesting way: it is deployed in each node (as a daemonset) and intercepts calls to the EC2 metadata API, checks whether the pod has an annotation granting a role, and in this case, it requests those temporary credentials to AWS and returns them to the caller. In order to do that, it need access to the host network (normally pods use a virtual interface). Kube2IAM has the ability to limit which pods in which namespaces are allowed to assume which roles (atm we're not limiting this.)

As an example, ark is a service running in the cluster. It needs permissions to create ec2 snapshots, as well as to write into certain S3 bucket. In order to grant those permissions to the pod running Ark using IAM roles we need to: 
1. create the IAM role and a trust policy which allows kubernetes workers to assume this role[1]. 
2. Add an annotation specifying this role[2] to its deployment.

In the future (probably not near future) AWS will come up with a solution integrated in EKS, but until now we can use kube2IAM. We've been using it in the IAM cluster since the begging and it works as expected.

The reason why I'm adding this now is because I read in the document created after the team meeting on Kubernetes that you arrived to the conclusion that this was one of the requirements for our EKS clusters. 
Here is a link to kube2IAM repo[3].

[1] https://github.com/mozilla-iam/iam-infra/blob/master/terraform/prod/us-west-2/services/ark/main.tf#L43
[2] https://github.com/mozilla-iam/iam-infra/blob/master/kubernetes/prod/us-west-2/ark/10-deployment-kube2iam.yaml#L16
[3] https://github.com/jtblin/kube2iam

**Comment by mozafrank** [comment]
thanks for the great write-up @The-smooth-operator we should move that to a markdown file for preservation.

**Review by mozafrank — APPROVED** [review]
👍

**Pull request merged**
